default:
  outputs:
    dev:
      dataset: connector
      keyfile:  "{{ env_var('TUVA_BIGQUERY_TOKEN') }}"
      location: US
      method: service-account
      priority: interactive
      project:  dev-ci-testing
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev