name: dbt_v1.4.6_snowflake_build_full_claims
on:
  workflow_dispatch:


env:
  DBT_TUVA_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_TUVA_SNOWFLAKE_ACCOUNT }}
  DBT_TUVA_CI_DATABASE: ${{ secrets.DBT_TUVA_CI_DATABASE }}
  DBT_SNOWFLAKE_CI_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_CI_PASSWORD }}
  DBT_SNOWFLAKE_CI_ROLE: ${{ secrets.DBT_SNOWFLAKE_CI_ROLE }}
  DBT_SNOWFLAKE_CI_SCHEMA: ${{ secrets.DBT_SNOWFLAKE_CI_SCHEMA }}
  DBT_SNOWFLAKE_CI_USER: ${{ secrets.DBT_SNOWFLAKE_CI_USER }}
  DBT_SNOWFLAKE_CI_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_CI_WAREHOUSE }}
  
jobs:
  claims_enabled:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: "dbt deps --profiles-dir ./profiles/snowflake"
          dbt_project_folder: "integration_tests"

      - name: dbt-debug
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: "dbt debug --profiles-dir ./profiles/snowflake"
          dbt_project_folder: "integration_tests"

      - name: dbt-build
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: 'dbt build --full-refresh --profiles-dir ./profiles/snowflake --vars {"input_database":"dev_ci_testing","input_schema":"input_layer","clinical_enabled":false,"claims_enabled":true}'
          dbt_project_folder: "integration_tests"

      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-build.outputs.result }}"
        shell: bash

  clinical_enabled:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: "dbt deps --profiles-dir ./profiles/snowflake"
          dbt_project_folder: "integration_tests"

      - name: dbt-debug
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: "dbt debug --profiles-dir ./profiles/snowflake"
          dbt_project_folder: "integration_tests"

      - name: dbt-build
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: 'dbt build --full-refresh --profiles-dir ./profiles/snowflake --vars {"input_database":"dev_ci_testing","input_schema":"input_layer","clinical_enabled":true,"claims_enabled":false}'
          dbt_project_folder: "integration_tests"

      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-build.outputs.result }}"
        shell: bash

  clinical_and_claims_enabled:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dbt-deps
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: "dbt deps --profiles-dir ./profiles/snowflake"
          dbt_project_folder: "integration_tests"

      - name: dbt-debug
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: "dbt debug --profiles-dir ./profiles/snowflake"
          dbt_project_folder: "integration_tests"

      - name: dbt-build
        uses: mwhitaker/dbt-action@v1.4.6
        with:
          dbt_command: 'dbt build --full-refresh --profiles-dir ./profiles/snowflake --vars {"input_database":"dev_ci_testing","input_schema":"input_layer","clinical_enabled":true,"claims_enabled":true}'
          dbt_project_folder: "integration_tests"

      - name: Get the result
        if: ${{ always() }}
        run: echo "${{ steps.dbt-build.outputs.result }}"
        shell: bash